### ISSUE TITLE
isOvercast improvement

### ISSUE THREAD

**Issue by jonferreira** [alisdairjsmyth/node-red-contrib-blindcontroller#10] opened 2017-03-26 10:50 UTC
Currently isOvercast (based on cloud threshold) *prevents* the logic from running when weather.clouds > cloudthreshould.

IMHO it would make more sense to make it simillar to temperaturethreshold , i.e. max cloud "rating" to which the blind will be fully closed.

For example if the window happens to be fully opened/closed and due to weather conditions weather.clouds go > cloudthreshould this would mean the blind logic would stop for the rest of the day.

**Comment by alisdairjsmyth** [comment] 2017-03-26 11:30
The intent of the current design is to minimise the extent to which direct sun light enters the room.  The temperature and cloud thresholds are (optional) overrides to the base calculation.

In the event of high forecasted temperatures, the temperature threshold keeps the blinds closed regardless of where the sun is in the sky.

The cloud threshold works on the basis that if it is sufficiently overcast the clouds rather than the blinds, are keeping the sun out of the room and therefore the blind doesn't need to be closed.

**Comment by jonferreira** [comment] 2017-03-26 11:33
Sure but unless if I'm missing something that wouldn't work either.

Say blind A is closed (sun not in window)
weather.clouds > cloudthreshould
Sun moves to blind A
Blind A won't open due to cloudthreshould

Unless I'm missing something?

So this could be a mode-defined behavior, i.e. if weather.clouds > cloudthreshould and mode = winter then "close blind" else if if weather.clouds > cloudthreshould and mode = summer then "open blind"

**Comment by jonferreira** [comment] 2017-03-26 11:38
Actually upon further look doesn't seem like cloudthershould is working at all in Winter mode so that's a bummer...

If I happen to code this myself would you accept the push? I understand your focus is mainly Summer mode while mine is Winter mode :)

**Comment by alisdairjsmyth** [comment] 2017-03-26 21:47
Neither threshold presently applies in Winter mode.  The present behaviour is ...
if winter mode
  if sun in window set to max open otherwise set to max closed
end if

Are you asking for the blinds to remain closed in winter mode if it is sufficiently overcast? i.e. it is gloomy outside, don't bother opening the blinds.  I am happy to accept a pull request - so long as we agree what the intended behaviour is.

**Comment by jonferreira** [comment] 2017-03-27 08:30
yes something like that...let me think on it, will get back to you later

**Comment by alisdairjsmyth** [comment] 2017-03-27 21:26
Feature incorporated into v4.3.0 through incorporation of pull request #7

**Closed by alisdairjsmyth** 2017-03-27 21:26 UTC
